version: '3'

services:
  siege:
    container_name: siege 
    build:
      context: ./requirements/siege
      dockerfile: Dockerfile
    image: siege:1.0
    # command: ["-c", "10", "-r", "10", "-t", "1S", "http://host.docker.internal:8000"]
    restart: always
    # ports:
    #   - "8000:8000"
    init: true
    # network_mode: host